[package]
name = "flowy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.33"
eframe = "0.25.0"
egui = "0.25.0"
epaint = "0.25.0"
